apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-world
  namespace: python-web
  labels:
    app: python-web-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-web-world
  strategy: {}
  template:
    metadata:
      labels:
        app: python-web-world
    spec:
      containers:
      - name: python-web-world
        image: .dkr.ecr..amazonaws.com/eks-fargate:world-7
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 20m
