apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-demo
  region: eu-west-2
  version: "1.21"

iam:
# serviceRoleArn: "arn:aws:iam::975820831807:role/XXeksServiceRole"
# fargatePodExecutionRoleARN: "arn:aws:iam::975820831807:role/eksPodRole"

fargateProfiles:
  - name: fp-default
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      # All workloads in the "kube-system" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: kube-system

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

########### VPC will be added here by script #############
